### ISSUE TITLE
Error when building from source

### ISSUE THREAD

**Issue by mschoenebeck** [cpacia/BitcoinCash-Wallet#10]
When building from source `make install` throws the following error:
```

cd cmd/bitcoincash && go install
# github.com/cpacia/BitcoinCash-Wallet/gui/bootstrap
../../gui/bootstrap/run.go:72:8: undefined: astilectron.EventNameWindowEventMessage
../../gui/bootstrap/run.go:92:6: w.Send undefined (type *astilectron.Window has no field or method Send)
makefile:2: recipe for target 'install' failed
make: *** [install] Error 2
```

Google didn't help. I try to build with go-1.9

**Comment by jchavannes** [comment]
@mschoenebeck I was able to fix the `astilectron` error by checking out the tag `v5.0` - https://github.com/asticode/go-astilectron/tree/v0.5.0

They must've introduced a breaking change to their master branch.
